### ISSUE TITLE
connecting cherrytree-react and redux

### ISSUE THREAD

**Issue by xrado** [KidkArolis/cherrytree-redux-react-example#2]
HI,

I'm trying to figure out, how to connect data fetching, redux and cherrytree-for-react. For now I added static dataFetch method to route component and middleware takes care of that and then pass data to component via props. But what I would like to do is dispatch data directly to redux store which will handle updating. The problem is if I dispatch data right after middleware ends its job, dispatch will trigger components update, before router renders out new components and unexpected can happen.
Do you have any suggest how to approach this?

btw ...thanks for great router!

**Comment by KidkArolis** [comment]
Good question! Sorry, I never got back to you.

I know it's probably not relevant anymore, but the way I've been trying to do this more recently is by making the middleware really simple - it just dispatches the new router state to redux. Then, I render the app based on the router state (instead of rendering via the middleware). Then, on componentDidMount, I initiate data fetches and dispatches. It looks something like this:

```
               +---> router
               |      +
               |      |
               |      v
    transition |     store  <----+
               |      +          |
               |      |          | dispatch
               |      v          |
               +---+ views  +——+
```

I've been working on wrapping this in a new package as we're still successfully using `cherrytree` in some of our React apps.

Anyways, interested to know what routing solution you're using now - did you join the dark side of react-router? Just kidding, it's a great router :)

**Comment by xrado** [comment]
I'm still using it, for all my react apps :), actually didn't found better router jet. I was trying react-router once or twice, but didn't like it. Moved to mobx now, but still didn't found solution that I'm satisfied with on store-router wiring. Somehow I always find some workaround, to make it work, but is far from perfect. Currently I'm splitting mobx stores for different pages, so transition to completely different page with middleware dataFetch wont affect or break the current page, until transition and all the collection data is complete to render a new page.
